version: '2'
services:
    girosdelsurjhipsterfull-app:
        image: girosdelsurjhipsterfull
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://girosdelsurjhipsterfull-mysql:3306/girosdelsurjhipsterfull?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    girosdelsurjhipsterfull-mysql:
        extends:
            file: mysql.yml
            service: girosdelsurjhipsterfull-mysql
